meme_help = """Syntax: meme keyword top text (optional: / bottom text). Supported keywords:
    "10 Guy": tenguy,
    "Afraid to Ask Andy": "afraid",
    "An Older Code Sir, But It Checks Out": "older",
    "Ancient Aliens Guy": "aag",
    "At Least You Tried": "tried",
    "Baby Insanity Wolf": "biw",
    "Baby, You've Got a Stew Going": "stew",
    "Bad Luck Brian": "blb",
    "But That's None of My Business": "kermit",
    "Butthurt Dweller": "bd",
    "Captain Hindsight": "ch",
    "Comic Book Guy": "cbg",
    "Condescending Wonka": "wonka",
    "Confession Bear": "cb",
    "Conspiracy Keanu": "keanu",
    "Dating Site Murderer": "dsm",
    "Do It Live!": "live",
    "Do You Want Ants?": "ants",
    "Doge": "doge",
    "Drake Always On Beat": "alwaysonbeat",
    "Ermahgerd": "ermg",
    "Facepalm": "facepalm",
    "First Try!": "firsttry",
    "First World Problems": "fwp",
    "Forever Alone": "fa",
    "Foul Bachelor Frog": "fbf",
    "Fuck Me, Right?": "fmr",
    "Futurama Fry": "fry",
    "Good Guy Greg": "ggg",
    "Hipster Barista": "hipster",
    "I Can Has Cheezburger?": "icanhas",
    "I Feel Like I'm Taking Crazy Pills": "crazypills",
    "I Guarantee It": "mw",
    "I Have No Idea What I'm Doing": "noidea",
    "I Immediately Regret This Decision!": "regret",
    "I Should Buy a Boat Cat": "boat",
    "I Should Not Have Said That": "hagrid",
    "I Would Be So Happy": "sohappy",
    "I am the Captain Now": "captain",
    "I'm Going to Build My Own Theme Park": "bender",
    "Inigo Montoya": "inigo",
    "Insanity Wolf": "iw",
    "It's A Trap!": "ackbar",
    "It's Happening": "happening",
    "It's Simple, Kill the Batman": "joker",
    "Jony Ive Redesigns Things": "ive",
    "Laughing Lizard": "ll",
    "Life... Finds a Way": "away",
    "Matrix Morpheus": "morpheus",
    "Member Berries": "mb",
    "Milk Was a Bad Choice": "badchoice",
    "Minor Mistake Marvin": "mmm",
    "Nothing To Do Here": "jetpack",
    "Oh, I'm Sorry, I Thought This Was America": "imsorry",
    "Oh, Is That What We're Going to Do Today?": "red",
    "One Does Not Simply Walk into Mordor": "mordor",
    "Oprah You Get a Car": "oprah",
    "Overly Attached Girlfriend": "oag",
    "Pepperidge Farm Remembers": "remembers",
    "Philosoraptor": "philosoraptor",
    "Probably Not a Good Idea": "jw",
    "Push it somewhere else Patrick": "patrick",
    "Roll Safe": "rollsafe",
    "Sad Barack Obama": "sad-obama",
    "Sad Bill Clinton": "sad-clinton",
    "Sad Frog / Feels Bad Man": "sadfrog",
    "Sad George Bush": "sad-bush",
    "Sad Joe Biden": "sad-biden",
    "Sad John Boehner": "sad-boehner",
    "Salt Bae": "saltbae",
    "Sarcastic Bear": "sarcasticbear",
    "Schrute Facts": "dwight",
    "Scumbag Brain": "sb",
    "Scumbag Steve": "ss",
    "Sealed Fate": "sf",
    "See? Nobody Cares": "dodgson",
    "Shut Up and Take My Money!": "money",
    "Skeptical Snake": "snek",
    "So Hot Right Now": "sohot",
    "So I Got That Goin' For Me, Which is Nice": "nice",
    "Socially Awesome Awkward Penguin": "awesome-awkward",
    "Socially Awesome Penguin": "awesome",
    "Socially Awkward Awesome Penguin": "awkward-awesome",
    "Socially Awkward Penguin": "awkward",
    "Stop Trying to Make Fetch Happen": "fetch",
    "Success Kid": "success",
    "Sudden Clarity Clarence": "scc",
    "Super Cool Ski Instructor": "ski",
    "That Would Be Great": "officespace",
    "The Most Interesting Man in the World": "interesting",
    "The Rent Is Too Damn High": "toohigh",
    "This is Bull, Shark": "bs",
    "This is Fine": "fine",
    "This is Sparta!": "sparta",
    "What is this, a Center for Ants?!": "center",
    "Why Not Both?": "both",
    "Winter is coming": "winter",
    "X all the Y": "xy",
    "X, X Everywhere": "buzz",
    "Xzibit Yo Dawg": "yodawg",
    "Y U NO Guy": "yuno",
    "Y'all Got Any More of Them": "yallgot",
    "You Should Feel Bad": "bad",
    "You Sit on a Throne of Lies": "elf",
    "You Were the Chosen One!": "chosen"
"""
swears = ["fuck", "shit", "nigger", "ass", "cock", "bitch", "retard"]
